### PR TITLE
4.1.0 dev

### LINKED ISSUE #240: Apply the "persistent variables style guide"
The "persistent variables style guide" is as follows.

## Introduction

I would like to add some formality to how we deal with persistent variables, such as GainDB. The objective is to simplify and beautify existing code, make it easier to enable/disable persistence for new variables, and to standardize the implementation specifics (such as order of operations) across all variables. 

During the lifetime of an Enlighten instance, such variables have three major life events: initialization, modification, and release.

### initialization
(1) check the .ini path 
(2) check memory (SpectrometerSettings, in case of multispec)
(3) check the eeprom
(4) use a hardcoded default

The search path should appear sequentially in code. Pseudo:
```python
# do something like this
def __init__(self):
    # initialize to None if necessary to silence a static analyzer
    self.gain_db = None
    if ini_available() and ini_has_path(sn, "gain_db"):
        self.gain_db = get_from_ini(sn, "gain_db")
    elif eeprom_has_value("gain_db_default"):
        self.gain_db = get_from_eeprom("gain_db_default")
    else:
        self.gain_db = 8

# do NOT do this
# this is a 'define and replace' pattern, often useful but not to be used to resolve persistent variables
def __init__(self):
    self.gain_db = 8
    if  eeprom_has_value("gain_db_default"):
        self.gain_db = get_from_eeprom("gain_db_default")
    if ini_available() and ini_has_path(sn, "gain_db"):
        self.gain_db = get_from_ini(sn, "gain_db")

# do NOT do this either
def __init__(self):
    self.gain_db = None
    # code (ini, hardcoded, eeprom) does not match search path (ini, eeprom, hardcoded)
    self.gain_db = get_from_ini(sn, "gain_db", default=8)
    if eeprom_has_value("gain_db_default"):
        self.gain_db = get_from_eeprom("gain_db_default")
```

### modification
(4) set scope-level variable `x = ...`
(5) set class-level variable  `self.x = ...`
(6) set application-level variable `self.ctl.multispec.set_state('x', ...)`
(7) set memory map of ini `self.ctl.config.set('x', ...)`
(8) propagate message to device driver `self.ctl.multispec.change_device_setting('x', ...)`
(9) propagate message to UI ` ctl.form.ui...setValue(...)`*

*This often needs to be wrapped by 'blockSignals' calls. `_quiet_set` should be moved a common UI helper module.

### release
(10) write modifications to ini. This happens when Enlighten is closed normally.

## Closing this issue

This issue is closed when all persistent variables conform to this standard. 
Notable discrepancies are 
- [x] how GainDB currently handles initialization: similarly to the first do NOT do example
* how the following do step (7) during the release phase
    - [x] boxcar halfwidth
    - [x] integration time
    - [x] gaindb

After this issue is closed, we can move the body text of the style guide into Github Discussions and then subsequently into Github Wiki. The move to Github Wiki will happen when several discussions are finalized and moved at once.

### LINKED ISSUE #291: enlighten.exe --help no longer works on Windows
Not sure when this broke, but isn't working now.  Also, `enlighten.exe --no-such-option` just silently fails, no message.

### LINKED ISSUE #324: Load Measurement broken
I was working on #108 when I noticed this. Attempting to load a measurement gives a "Loaded 1 measurement" but nothing shows up.

image

```
2023-10-12 17:11:18,304 [0x00004db8] enlighten.parser.ColumnFileParser ERROR    unable to convert to datetime: [['2022-09-29 15:59:28.481182']]
2023-10-12 17:11:18,304 [0x00004db8] enlighten.parser.ColumnFileParser DEBUG    active_pixels_horizontal = 1652
2023-10-12 17:11:18,304 [0x00004db8] enlighten.measurement.MeasurementFactory ERROR    failed to parse file C:/Users/sbee/Documents/EnlightenSpectra/New SIG Library/Methanol.csv
Traceback (most recent call last):
  File "Y:\projects\Enlighten-B\enlighten\measurement\MeasurementFactory.py", line 263, in create_from_file
    measurements = [ self.create_from_columnar_file(pathname, encoding=encoding) ]
  File "Y:\projects\Enlighten-B\enlighten\measurement\MeasurementFactory.py", line 410, in create_from_columnar_file
    return parser.parse()
  File "Y:\projects\Enlighten-B\enlighten\parser\ColumnFileParser.py", line 51, in parse
    self.post_process_metadata()
  File "Y:\projects\Enlighten-B\enlighten\parser\ColumnFileParser.py", line 204, in post_process_metadata
    state.boxcar_half_width = int(self.get_safe_float(key))
  File "Y:\projects\Enlighten-B\enlighten\parser\ColumnFileParser.py", line 89, in get_safe_float
    if len(v.strip()) == 0:
AttributeError: 'list' object has no attribute 'strip'
2023-10-12 17:11:18,305 [0x00004db8] enlighten.measurement.Measurements DEBUG    create_from_file: no Measurements parsed from C:/Users/sbee/Documents/EnlightenSpectra/New SIG Library/Methanol.csv
2023-10-12 17:11:18,305 [0x00004db8] enlighten.file_io.FileManager DEBUG    scheduling load of the next file
2023-10-12 17:11:18,306 [0x00004db8] enlighten.device.Multispec DEBUG    Multispec.current_spectrometer: self.device_id is None
```

This should be corrected and the surrounding try-except should make a msgbox upon failure instead of silently passing the traceback to the enlighten.log.

### PR DESCRIPTION
**Pull request by samiebee43**
This draft exists to keep track of issues that should close when 4.1.0-dev is merged to main

- close #324 
- close #291 
- close #240

### CODE REVIEW

**Comment by samiebee43** [comment]
4.1.0-dev has diverged significantly from main. We've made a lot of progress. This needs a good round of testing.

**Review by mzieg — APPROVED** [review]

**Comment by mzieg** [comment]
> This needs a good round of testing.

True, but the testing can be on the 4.1.0 branch, not main.

**Comment by samiebee43** [comment]
Agreed! I did not want to merge this main yet. Converted to draft.

**Comment by samiebee43** [comment]
hide_console still doesn't work on Win11

**Pull request closed without merging**
